In [ ]:
#Omar - Alsubgh - NLP - 2210002182 - LAB 1

In [1]:
import nltk

In [2]:
import kagglehub

# IMDB Dataset of 50K Movie Reviews
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

c:\Users\Oalsu\OneDrive\Desktop\NLP-Labs\Lab1\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Oalsu\.cache\kagglehub\datasets\lakshmi25npathi\imdb-dataset-of-50k-movie-reviews\1.archive...

100%|██████████| 25.7M/25.7M [00:08<00:00, 3.32MB/s]

Extracting files...

Path to dataset files: C:\Users\Oalsu\.cache\kagglehub\datasets\lakshmi25npathi\imdb-dataset-of-50k-movie-reviews\versions\1

In [6]:
from pathlib import Path
import pandas as pd

# The dataset folder and file both share the same name.
# Read the CSV file inside the folder, not the directory itself.
csv_path = Path("IMDB Dataset.csv") / "IMDB Dataset.csv"
df = pd.read_csv(csv_path)

# Show the first few rows
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [9]:
# Check class distribution
print(df['sentiment'].value_counts())

sentiment
positive    25000
negative    25000
Name: count, dtype: int64